### ISSUE TITLE
rain_blocking.json doesn't contain all blocks except air/cave_air

### ISSUE THREAD

**Issue by IceFreez3r** [CloudWolfYT/Sky-Detection-Datapack#1]
> Updated to 1.18 blocks but rain_blocking now **only does not have**:
air and cave_air
you can remove whatever you see fit.

Just compare the number of lines in [all_blocks.json](https://github.com/CloudWolfYT/Sky-Detection-Datapack/blob/main/data/minecraft/tags/blocks/all_blocks.json)(902) and [rain_block.ing.json](https://github.com/CloudWolfYT/Sky-Detection-Datapack/blob/main/data/minecraft/tags/blocks/rain_blocking.json)(615). rain_blocking is definitely missing some blocks or the Readme is wrong

**Comment by CloudWolfYT** [comment]
read the main readme of the github, i swapped it to be probable blocks
